// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0lbtI4BNlBZFV6bW9xUSx0gOOoj2ExE4',
    appId: '1:974460272163:web:e228c2b7543f57d3ed3b96',
    messagingSenderId: '974460272163',
    projectId: 'fitness-7238c',
    authDomain: 'fitness-7238c.firebaseapp.com',
    storageBucket: 'fitness-7238c.firebasestorage.app',
    measurementId: 'G-V6CDGRKX6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5883MHRrJHmQz-pxWbpQ_kvy669GnlYY',
    appId: '1:974460272163:android:9ca1d2d9a759faeeed3b96',
    messagingSenderId: '974460272163',
    projectId: 'fitness-7238c',
    storageBucket: 'fitness-7238c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrOXazcKWcV3czPqUSqaQP7uesMKy6I60',
    appId: '1:974460272163:ios:62c4f33615b7e967ed3b96',
    messagingSenderId: '974460272163',
    projectId: 'fitness-7238c',
    storageBucket: 'fitness-7238c.firebasestorage.app',
    iosClientId: '974460272163-jcukp1vr45qq4ihrhmele6anc54293me.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrOXazcKWcV3czPqUSqaQP7uesMKy6I60',
    appId: '1:974460272163:ios:62c4f33615b7e967ed3b96',
    messagingSenderId: '974460272163',
    projectId: 'fitness-7238c',
    storageBucket: 'fitness-7238c.firebasestorage.app',
    iosClientId: '974460272163-jcukp1vr45qq4ihrhmele6anc54293me.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0lbtI4BNlBZFV6bW9xUSx0gOOoj2ExE4',
    appId: '1:974460272163:web:5ec41a33e4a655fced3b96',
    messagingSenderId: '974460272163',
    projectId: 'fitness-7238c',
    authDomain: 'fitness-7238c.firebaseapp.com',
    storageBucket: 'fitness-7238c.firebasestorage.app',
    measurementId: 'G-KH2M1LSBFN',
  );
}
